name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest 2 Ubuntu versions with containers
          - os: ubuntu-latest
            name: Ubuntu Latest
            container: ubuntu:22.04
          - os: ubuntu-24.04
            name: Ubuntu 24.04
            container: ubuntu:24.04
          # Latest 2 macOS versions
          - os: macos-latest
            name: macOS Latest
          - os: macos-14
            name: macOS 14
          # Latest 2 Windows versions
          - os: windows-latest
            name: Windows Latest
          - os: windows-2022
            name: Windows 2022

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    container: ${{ matrix.container }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Conan (non-Linux)
      if: runner.os != 'Linux'
      run: |
        python -m pip install --upgrade pip
        pip install conan

    - name: Set up Python (Linux)
      if: runner.os == 'Linux'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Conan (Linux)
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip
        pip install conan

    - name: Get Conan home directory
      id: conan-home
      shell: bash
      run: |
        echo "path=$(conan config home)" >> $GITHUB_OUTPUT

    - name: Cache Conan packages
      uses: actions/cache@v4
      with:
        path: ${{ steps.conan-home.outputs.path }}
        key: conan-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          conan-${{ runner.os }}-

    - name: Configure Conan
      run: |
        conan profile detect

    - name: Build project
      shell: bash
      run: |
        chmod +x build.sh
        if [ "$RUNNER_OS" = "Linux" ]; then
          # For Linux, run conan directly (no sudo needed in container)
          conan profile detect --force
          conan install . --output-folder=build --build=missing -c tools.system.package_manager:mode=install
          source build/conanbuild.sh
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake
          cmake --build build -j$(nproc)
        elif [ "$RUNNER_OS" = "Windows" ]; then
          # Windows doesn't need sudo, just run conan directly
          conan profile detect --force
          conan install . --output-folder=build --build=missing
          source build/conanbuild.sh
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake
          cmake --build build -j$(nproc)
        else
          # macOS and others use the build script
          ./build.sh
        fi
        echo "Build completed. Checking build directory:"
        ls -la build/ || echo "Build directory not found"
        ls -la build/bin/ || echo "Bin directory not found"

    - name: Test executable (Linux/macOS)
      if: matrix.os != 'windows-latest' && matrix.os != 'windows-2022'
      run: |
        cd build
        ./bin/opencv_cpp_starter
        ls -la *.png

    - name: Test executable (Windows)
      if: matrix.os == 'windows-latest' || matrix.os == 'windows-2022'
      shell: pwsh
      run: |
        echo "Current directory: $(Get-Location)"
        echo "Build directory contents:"
        Get-ChildItem build/ -ErrorAction SilentlyContinue || echo "Build directory not found"
        echo "Bin directory contents:"
        Get-ChildItem build/bin/ -ErrorAction SilentlyContinue || echo "Bin directory not found"
        cd build
        ./bin/opencv_cpp_starter.exe
        Get-ChildItem *.png

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-${{ matrix.name }}
        path: |
          build/
          *.png
        retention-days: 7
