name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows latest 2 versions
          - os: windows-2025
            name: "Windows Server 2025"
          - os: windows-2022
            name: "Windows Server 2022"
          
          # Ubuntu latest 2 versions
          - os: ubuntu-24.04
            name: "Ubuntu 24.04"
          - os: ubuntu-22.04
            name: "Ubuntu 22.04"
          
          # macOS latest 2 versions
          - os: macos-15
            name: "macOS 15 (Sequoia)"
          - os: macos-14
            name: "macOS 14 (Sonoma)"

    name: Build on ${{ matrix.name }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Create ccache directories
      run: |
        mkdir -p ~/.ccache
        mkdir -p ~/.cache/ccache

    - name: Setup ccache
      uses: actions/cache@v4
      with:
        path: |
          ~/.ccache
          ~/.cache/ccache
        key: ${{ matrix.os }}-ccache-${{ hashFiles('xmake.lua') }}
        restore-keys: |
          ${{ matrix.os }}-ccache-

    - name: Cache xmake packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.xmake
          ~/AppData/Local/.xmake
        key: ${{ matrix.os }}-xmake-${{ hashFiles('xmake.lua') }}
        restore-keys: |
          ${{ matrix.os }}-xmake-

    - name: Make build script executable
      run: chmod +x build_xmake.py

    - name: Build and test using build script
      run: |
        # Build the project
        ./build_xmake.py
        
        # Run the application to test it works
        ./build_xmake.py run

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opencv_cpp_starter-${{ matrix.os }}
        path: |
          build/
          build/**/*
        retention-days: 7
